### ISSUE TITLE
Widget follow dark/light-Theme

### ISSUE THREAD

**Issue by lomenzel** [hoppjan/LuebeckMensaWidget#6]
Widget is always displayd in dark mode but shuld follow the system preference

**Comment by hoppjan** [comment]
I could not figure out how to do widget theming in Jetpack Compose Glance.
The usual way to determine the theme does not work in the widget.

A workaround could be to ask for user preference.
#9 will need the infrastructure for user preferences, so this will be deprioritized until that issue is closed.
